[package]
name = "beg2dither"
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = ["Edna Baud <ednabaud@gmail.com>"]
description = "An image dithering TUI with live preview"
readme = "README.md"
keywords = ["terminal", "tui", "dither"]
categories = ["graphics"]
repository = "https://github.com/northernmarshes/beg2dither"
homepage = "https://github.com/northernmarshes/beg2dither"

[[bin]]
name = "b2d"
path = "src/main.rs"

[dependencies]
crossterm = "0.29.0"
dithers = "0.1.0"
image = "0.25.10"
ratatui = "0.30.2"
ratatui-explorer = "0.3.0"
ratatui-image = "11.0.6"
